services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 8000:8000
  
  middleware:
    build: 
      context: .
      dockerfile: middleware.Dockerfile
    env_file: ".env"
    ports:
      - 8001:8000
