services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - API_BASE_URL=http://middleware:8000
      - API_API_KEY=abc
      - CACHE_URL=redis://redis
      - DATABASE_URL=postgresql+asyncpg://postgres:pgpasswd@postgres/postgres
    networks:
      - public
      - private
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./src
          target: /src
          action: sync
        - path: ./src/frontend
          target: /src/frontend
          action: sync
        - path: ./src/aquasensor_backend
          target: /src/aquasensor_backend
          action: sync+restart

  middleware:
    build:
      context: .
      dockerfile: middleware.Dockerfile
    ports:
      - 8001:8000
    networks:
      - private
    environment:
      - MIDDLEWARE_API_KEY=abc
    env_file:
      - envs/middleware.env

  redis:
    image: redis:8.0-M03-alpine
    volumes:
      - red:/data
    networks:
      - private
    ports:
      - 6379:6379

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpasswd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - private
    volumes:
      - pgdata:/var/lib/postgresql/data

  streamer:
    build:
      context: .
      dockerfile: stream-processor.Dockerfile
    restart: always
    networks:
      - private
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgresql+asyncpg://postgres:pgpasswd@postgres/postgres
    env_file:
      - ./envs/streamer.env

volumes:
  red:
    external: false
  pgdata:
    external: false
  influxdb_data:
    external: false

networks:
  public:
    external: false
  private:
    external: false