services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - API_BASE_URL=http://middleware:8000
      - API_API_KEY=abc
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./src
          target: /src
          action: sync
        - path: ./src/frontend
          target: /src/frontend
          action: sync
        - path: ./src/aquasensor_backend
          target: /src/aquasensor_backend
          action: sync
  middleware:
    build: 
      context: .
      dockerfile: middleware.Dockerfile
    env_file: ".env"

  redis:
    image: redis:8.0-M03-alpine
    volumes:
      - red:/data
    ports:
      - 6379:6379
      - 6380:6380
volumes:
  red:
