[project]
name = "mqtt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gmqtt>=0.7.0",
    "influxdb-client>=1.48.0",
    "pydantic>=2.10.6",
]
